spring.application.name=xxx_crud
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PWD}
spring.main.banner-mode=off
logging.pattern.console=%d{MM-dd HH:mm} %m%n
server.servlet.session.timeout=30d
